using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameManager : MonoBehaviour {

    private static GameManager S_INSTANCE = null;

    public static GameManager INSTANCE {
        get {
            if (S_INSTANCE == null) {
                S_INSTANCE = FindObjectOfType(typeof(GameManager)) as GameManager;
            }

            if (S_INSTANCE == null) {
                GameObject obj = new GameObject("AutoGenerated: GameManager");
                S_INSTANCE = obj.AddComponent(typeof(GameManager)) as GameManager;
                Debug.LogError("Could not locate an GameManager object. \n GameManager was Generated Automatically.");
            }

            return S_INSTANCE;
        }
    }

}